export const FontIcons = {
    Home: '',
    Swiper: '',
    Button: '',
    "Floating Action Button Example": '',
    TextInput: '',
    "Modal Screen Example": '',
    "Light Box Screen Example": '',
    "Tab View Example": '',
    "TimeLine View Example": '',
    "Chart Example": '',
    "ListScreen": '',
    "Push Notification": '',
    "Card View": '',
};
